spring:
  application:
    name: clothing

  datasource:
    url: jdbc:mysql://${MYSQLHOST:hayabusa.proxy.rlwy.net}:${MYSQLPORT:10313}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:iJSeNgb1TDvHAEpSAgwltRohTToSkIEI}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}